version: 0.2

phases:
  build:
    commands:
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - target/testDeployment-0.0.1-SNAPSHOT.jar
  discard-paths: true