version: 0.2

phases:
  build:
    commands:
      - mvn clean package
      - mkdir artifacts
      - cp target/test-deployment.jar artifacts/
      - zip -r test-deployment.zip artifacts/*

artifacts:
  files:
    - test-deployment.zip
