version: 0.2

phases:
  install:
    runtime-versions:
      java: 17
  build:
    commands:
      - mvn compile

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - target/test-deployment.jar
  discard-paths: yes