version: 0.2

phases:

  build:
    commands:
      - mvn build

  test:
    commands:
      - mvn test

  package:
    commands:
      - mvn clean package
      - mkdir artifacts
      - cp target/test-deployment.jar artifacts/
      - zip -r test-deployment.zip artifacts/*

artifacts:
  files:
    - test-deployment.zip
