version: 0.2

phases:
  build:
    commands:
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed successfully"
      - cp target/*.jar application.jar

artifacts:
  files:
    - application.jar
  discard-paths: true