version: 0.2

phases:
  build:
    commands:
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed successfully"

artifacts:
  files:
    - target/test-deployment.jar
  discard-paths: yes